# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Rnorm <- function(n, m = 0.0, s = 1.0) {
    .Call(`_NormGen_Rnorm`, n, m, s)
}

