# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Parallel Pseudo-Normal Random Number Generator
#' @description Generates pseudo-random numbers from a normal distribution using multiple threads.
#' @param n number of samples
#' @param mean distribution mean
#' @param sd distribution standard deviation
#' @param seed generator seed
#' @export
parallel_Rnorm <- function(n, mean = 0.0, sd = 1.0, seed = 12345L) {
    .Call(`_NormGen_parallel_Rnorm`, n, mean, sd, seed)
}

#' @title Single-threaded Pseudo-Normal Random Number Generator
#' @description Original single-threaded implementation of the NormGen quantile mapping algorithm.
#' @param n number of samples
#' @param m distribution mean
#' @param s distribution standard deviation
#' @export
Rnorm <- function(n, m = 0.0, s = 1.0) {
    .Call(`_NormGen_Rnorm`, n, m, s)
}

